export enum EnumErrors {
  AGENT_ID_SHOULD_PROVIDED = "parameter agentId should be provided",
  AGENT_NOT_CONFIGURED = "AGENT_NOT_CONFIGURED",
  CONFIG_SHOULD_PROVIDED = "CONFIG_SHOULD_PROVIDED",
  CONTACT_SECRET_SHOULD_PROVIDED = "CONTACT_SECRET_SHOULD_PROVIDED",
  DEPARTMENT_ID_SHOULD_PROVIDED = "DEPARTMENT_ID_SHOULD_PROVIDED",
  EXTERNAL_CONTACT_SECRET_SHOULD_PROVIDED = "EXTERNAL_CONTACT_SECRET_SHOULD_PROVIDED",
  INVITE_PARAMETERS_ALL_UNDEFINED = "INVITE_PARAMETERS_ALL_UNDEFINED",
  SECRET_TYPE_NOT_SUPPORTED = "secret type not supported.",
  GET_ACCESS_TOKEN_METHOD_SHOULD_PROVIDED = "GET_ACCESS_TOKEN_METHOD_SHOULD_PROVIDED"
}
